language: node_js
arch:
    - amd64
    - ppc64le
notifications:
    email:
        on_success: never
        on_failure: change
node_js:
    - "14"
    - "15"
    - "16"
cache:
    npm: true
script:
    - npm install -g typescript
    - npm run build
    - npm run test
